#ifndef ELEMENT_TYPE_HH
#define ELEMENT_TYPE_HH

/* Level elements */
enum element_type {
	/* These correspond exactly to Supaplex and its level format */
	ELEMENT_SPACE,
	ELEMENT_ZONK,
	ELEMENT_BASE,
	ELEMENT_MURPHY,
	ELEMENT_INFOTRON,
	ELEMENT_CHIP_SQUARE,
	ELEMENT_WALL,
	ELEMENT_EXIT,
	ELEMENT_DISK_ORANGE,
	ELEMENT_PORT_LEFT_TO_RIGHT,
	ELEMENT_PORT_UP_TO_DOWN,
	ELEMENT_PORT_RIGHT_TO_LEFT,
	ELEMENT_PORT_DOWN_TO_UP,
	ELEMENT_PORT_SPECIAL_LEFT_TO_RIGHT,
	ELEMENT_PORT_SPECIAL_UP_TO_DOWN,
	ELEMENT_PORT_SPECIAL_RIGHT_TO_LEFT,
	ELEMENT_PORT_SPECIAL_DOWN_TO_UP,
	ELEMENT_SNIK_SNAK,
	ELEMENT_DISK_YELLOW,
	ELEMENT_TERMINAL,
	ELEMENT_DISK_RED,
	ELEMENT_PORT_VERTICAL,
	ELEMENT_PORT_HORIZONTAL,
	ELEMENT_PORT_CROSS,
	ELEMENT_ELECTRON,
	ELEMENT_BUG,
	ELEMENT_CHIP_HORIZONTAL_LEFT,
	ELEMENT_CHIP_HORIZONTAL_RIGHT,
	ELEMENT_HARDWARE_1,
	ELEMENT_HARDWARE_LAMP_GREEN,
	ELEMENT_HARDWARE_LAMP_BLUE,
	ELEMENT_HARDWARE_LAMP_RED,
	ELEMENT_HARDWARE_2,
	ELEMENT_HARDWARE_3,
	ELEMENT_HARDWARE_4,
	ELEMENT_HARDWARE_5,
	ELEMENT_HARDWARE_6,
	ELEMENT_HARDWARE_7,
	ELEMENT_CHIP_VERTICAL_TOP,
	ELEMENT_CHIP_VERTICAL_BOTTOM,
	ELEMENT_WALL_INVISIBLE,

	NR_STATIC_ELEMENTS,

	/* I don't have the original Supaplex source code, so these numbers
	 * are completely particular to this clone. */
	ELEMENT_RESERVED,

	ELEMENT_MURPHY_STANDING,
	ELEMENT_MURPHY_MOVING,

	ELEMENT_ZONK_FALLING_DOWN_TOP,
	ELEMENT_ZONK_FALLING_DOWN_BOTTOM,
	ELEMENT_ZONK_ROLLING_LEFT_LEFT,
	ELEMENT_ZONK_ROLLING_LEFT_RIGHT,
	ELEMENT_ZONK_ROLLING_RIGHT_RIGHT,
	ELEMENT_ZONK_ROLLING_RIGHT_LEFT,

	NR_ELEMENTS,
};

#endif
