#ifndef TILE_HH
#define TILE_HH

/* Graphics tiles */
enum tile {
	TILE_SPACE,
	TILE_ZONK,
	TILE_BASE,
	TILE_MURPHY,
	TILE_INFOTRON,
	TILE_CHIP_SQUARE,
	TILE_WALL,
	TILE_EXIT,
	TILE_DISK_ORANGE,
	TILE_PORT_LEFT_TO_RIGHT,
	TILE_PORT_UP_TO_DOWN,
	TILE_SNIK_SNAK,
	TILE_DISK_YELLOW,
	TILE_TERMINAL,
	TILE_DISK_RED,
	TILE_PORT_VERTICAL,
	TILE_PORT_HORIZONTAL,
	TILE_PORT_CROSS,
	TILE_ELECTRON,

	TILE_CHIP_HORIZONTAL_LEFT,
	TILE_CHIP_HORIZONTAL_RIGHT,
	TILE_HARDWARE_1,
	TILE_HARDWARE_LAMP_GREEN,
	TILE_HARDWARE_LAMP_BLUE,
	TILE_HARDWARE_LAMP_RED,
	TILE_HARDWARE_2,
	TILE_HARDWARE_3,
	TILE_HARDWARE_4,
	TILE_HARDWARE_5,
	TILE_HARDWARE_6,
	TILE_HARDWARE_7,
	TILE_CHIP_VERTICAL_TOP,
	TILE_CHIP_VERTICAL_BOTTOM,

	/* Must be last element */
	NR_TILES,
};

#endif
